meta_product_name: "FluentChinese"
meta_title: "FluentChinese - Climb The Great Wall In No Time At All"
meta_description: "A six-month language learning bootcamp to develop confidence in speaking Chinese"
meta_image: "great-wall-banner-og-image.jpg" # should exist in `app/assets/images/`
