meta_product_name: "FluentChinese"
meta_title: "FluentChinese - Climb The Great Wall In No Time At All"
meta_description: "A six-month language learning bootcamp to develop confidence in speaking Chinese"
meta_image: "https://res.cloudinary.com/dbevdhp4h/image/upload/v1647124130/great-wall-banner-og-image_bz0lc2.jpg" # should exist in `app/assets/images/`
